export type ICONS =
  | 'add'
  | 'alert'
  | 'arrowLeft'
  | 'bin'
  | 'camera'
  | 'check'
  | 'chevronUp'
  | 'chevronDown'
  | 'chevronLeft'
  | 'chevronRight'
  | 'christmasBells'
  | 'close'
  | 'edit'
  | 'fullscreenEnter'
  | 'fullscreenExit'
  | 'graph'
  | 'hamburgerMenu'
  | 'info'
  | 'learn'
  | 'logout'
  | 'moments'
  | 'paperPlane'
  | 'photo'
  | 'play'
  | 'seeTheGood'
  | 'share'
  | 'teach';

export type ICONS_LIGHT =
  | 'barGraph'
  | 'bookPages'
  | 'buttonRecord'
  | 'calendarHeart'
  | 'christmasBells'
  | 'download'
  | 'groupUsers'
  | 'handExpand'
  | 'houseEntrance'
  | 'laptopSmiley'
  | 'learn'
  | 'seeTheGood'
  | 'positiveCV'
  | 'teach';

export type ICONS_BOLD = 'add' | 'arrowRight' | 'play';
